"use client";
import {FormEvent,useEffect,useState} from "react";
type Profile={role:"admin"|"data_manager"|"validator"|"analyst"|"viewer";full_name:string|null;active:boolean};
type AuthState={token:string;user:{id:string;email?:string};profile:Profile}|null;
const supabaseUrl="https://strffffxecbnwkeqgttd.supabase.co",publishableKey=process.env.NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY||"";
const headers=(token?:string)=>({apikey:publishableKey,Authorization:`Bearer ${token||publishableKey}`});
const readResponse=async(res:Response)=>{const text=await res.text();try{return JSON.parse(text)}catch{throw new Error(`O serviço de autenticação respondeu em formato inesperado (${res.status}). Verifique a Publishable Key no Vercel.`)}};
export default function DataManagement(){
 const[upload,setUpload]=useState(false),[authOpen,setAuthOpen]=useState(false),[file,setFile]=useState<File|null>(null),[stage,setStage]=useState(0),[auth,setAuth]=useState<AuthState>(null),[email,setEmail]=useState(""),[password,setPassword]=useState(""),[message,setMessage]=useState(""),[busy,setBusy]=useState(false);
 const configured=Boolean(supabaseUrl&&publishableKey),canUpload=Boolean(auth?.profile.active&&["admin","data_manager"].includes(auth.profile.role));
 useEffect(()=>{const saved=sessionStorage.getItem("ice-mz-auth");if(saved)try{setAuth(JSON.parse(saved))}catch{sessionStorage.removeItem("ice-mz-auth")}},[]);
 const close=()=>{setUpload(false);setStage(0);setFile(null);setMessage("")};
 const signIn=async(e:FormEvent)=>{e.preventDefault();setBusy(true);setMessage("");try{if(!configured)throw new Error("A Publishable Key do Supabase não está configurada.");const res=await fetch(`${supabaseUrl}/auth/v1/token?grant_type=password`,{method:"POST",headers:{...headers(),"Content-Type":"application/json"},body:JSON.stringify({email,password})});const session=await readResponse(res);if(!res.ok)throw new Error(session.error_description||session.msg||"Credenciais inválidas.");const profileRes=await fetch(`${supabaseUrl}/rest/v1/profiles?user_id=eq.${session.user.id}&select=role,full_name,active&limit=1`,{headers:headers(session.access_token)});const profiles=await readResponse(profileRes);if(!profileRes.ok||!profiles[0])throw new Error("Conta autenticada, mas sem perfil ICE-MZ activo.");const next={token:session.access_token,user:session.user,profile:profiles[0]} as AuthState;setAuth(next);sessionStorage.setItem("ice-mz-auth",JSON.stringify(next));setAuthOpen(false);setPassword("")}catch(err){setMessage(err instanceof Error?err.message:"Não foi possível iniciar sessão.")}finally{setBusy(false)}};
 const signUp=async()=>{setBusy(true);setMessage("");try{if(!configured)throw new Error("A Publishable Key do Supabase não está configurada.");if(email.toLowerCase()!=="sergiom.ndimande@gmail.com")throw new Error("O primeiro Administrador deve usar o e-mail autorizado.");if(password.length<8)throw new Error("A palavra-passe deve ter pelo menos 8 caracteres.");const res=await fetch(`${supabaseUrl}/auth/v1/signup`,{method:"POST",headers:{...headers(),"Content-Type":"application/json"},body:JSON.stringify({email,password,data:{full_name:"Sérgio Ndimande"}})});const result=await readResponse(res);if(!res.ok)throw new Error(result.msg||result.error_description||"Não foi possível criar a conta.");setMessage("Conta criada. Confirme o e-mail recebido e depois inicie sessão.");setPassword("")}catch(err){setMessage(err instanceof Error?err.message:"Não foi possível criar a conta.")}finally{setBusy(false)}};
 const signOut=async()=>{if(auth)await fetch(`${supabaseUrl}/auth/v1/logout`,{method:"POST",headers:headers(auth.token)}).catch(()=>null);setAuth(null);sessionStorage.removeItem("ice-mz-auth")};
 const beginUpload=()=>{if(!canUpload){setAuthOpen(true);return}setUpload(true)};
 const storeFile=async()=>{if(!file||!auth||!canUpload)return;setBusy(true);setMessage("");try{const safe=file.name.replace(/[^a-zA-Z0-9._-]/g,"_"),path=`${auth.user.id}/${Date.now()}-${safe}`;const uploadRes=await fetch(`${supabaseUrl}/storage/v1/object/ice-source-files/${path}`,{method:"POST",headers:{...headers(auth.token),"Content-Type":file.type||"application/octet-stream","x-upsert":"false"},body:file});if(!uploadRes.ok){const e=await uploadRes.json().catch(()=>({}));throw new Error(e.message||"Falha no envio do ficheiro.")}const flow=/imp/i.test(file.name)?"IMP":"EXP",found=file.name.match(/20\d{2}/),reference_year=found?Number(found[0]):new Date().getFullYear();const datasetRes=await fetch(`${supabaseUrl}/rest/v1/datasets`,{method:"POST",headers:{...headers(auth.token),"Content-Type":"application/json",Prefer:"return=minimal"},body:JSON.stringify({flow,reference_year,file_name:file.name,storage_path:path,uploaded_by:auth.user.id,status:"uploaded"})});if(!datasetRes.ok)throw new Error("Ficheiro guardado, mas o catálogo não pôde ser actualizado.");setStage(2);setMessage("Ficheiro guardado com segurança e enviado para validação.")}catch(err){setMessage(err instanceof Error?err.message:"Não foi possível carregar o ficheiro.")}finally{setBusy(false)}};
 return <><div className="management-status"><i className={configured?"online":""}/><span>{configured?"Supabase ligado":"Ligação por configurar"}</span>{auth&&<><b>{auth.profile.full_name||auth.user.email} · {auth.profile.role}</b><button onClick={signOut}>Sair</button></>}</div><div className="management-grid"><article className="management-card protected"><span>BASE INTEGRAL · ACESSO PROTEGIDO</span><h3>Registos completos e ficheiros-fonte</h3><p>NUIT e nomes dos importadores/exportadores permanecem apenas nesta camada. O acesso é concedido por perfil e todas as operações ficam registadas.</p><button className="login" onClick={()=>setAuthOpen(true)}>{auth?"Ver perfil e permissões":"Entrar na área reservada"} ↗</button></article><article className="management-card public-data"><span>BASE PÚBLICA · SEM IDENTIFICADORES</span><h3>Dados analíticos para reutilização</h3><p>Download em CSV sem NUIT, nome do importador ou nome do exportador, acompanhado por dicionário de dados.</p><div><a href="/downloads/Base_Publica_ICE_MZ_2022_2025.csv" download>Descarregar CSV ↓</a><a href="/downloads/Dicionario_Base_Publica_ICE_MZ.txt" download>Dicionário ↓</a></div></article></div><section className="upload-section management-upload"><div><span>GESTÃO AUTOMÁTICA DE DADOS</span><h2>Carregar dados de 2026 em diante</h2><p>Disponível apenas para Administrador e Gestor de dados. O ficheiro é guardado no espaço privado e catalogado antes da validação.</p></div><button onClick={beginUpload}>＋ Carregar novo ficheiro</button><ol><li><b>1</b>Carregar Excel ou CSV</li><li><b>2</b>Validar e normalizar</li><li><b>3</b>Calcular índices</li><li><b>4</b>Aprovar e publicar</li></ol></section>
 {authOpen&&<div className="modal-backdrop" role="dialog" aria-modal="true" aria-label="Acesso reservado"><form className="upload-modal auth-modal" onSubmit={signIn}><button type="button" className="modal-close" onClick={()=>{setAuthOpen(false);setMessage("")}}>×</button><span>ÁREA RESERVADA ICE-MZ</span><h3>{auth?"Perfil autenticado":"Entrar ou criar a conta inicial"}</h3>{auth?<div className="validation-list"><p>✓ {auth.profile.full_name||auth.user.email}</p><p>Perfil: <b>{auth.profile.role}</b></p><p>Estado: {auth.profile.active?"Activo":"Inactivo"}</p><button type="button" onClick={signOut}>Terminar sessão</button></div>:<><label className="auth-field">E-mail<input type="email" value={email} onChange={e=>setEmail(e.target.value)} placeholder="sergiom.ndimande@gmail.com" required/></label><label className="auth-field">Palavra-passe<input type="password" value={password} onChange={e=>setPassword(e.target.value)} minLength={8} required/></label>{message&&<p className="form-message">{message}</p>}<div className="auth-actions"><button disabled={busy}>{busy?"A processar…":"Entrar →"}</button><button type="button" disabled={busy} onClick={signUp}>Criar primeira conta</button></div></>}</form></div>}
 {upload&&<div className="modal-backdrop" role="dialog" aria-modal="true" aria-label="Carregar novo ficheiro"><div className="upload-modal"><button className="modal-close" onClick={close}>×</button><span>NOVO CONJUNTO DE DADOS · ÁREA PROTEGIDA</span><h3>Carregamento seguro</h3><div className="upload-steps"><i className={stage>=0?"active":""}>1</i><i className={stage>=1?"active":""}>2</i><i className={stage>=2?"active":""}>3</i></div>{stage===0&&<><label className="dropzone"><input type="file" accept=".xlsx,.csv" onChange={e=>setFile(e.target.files?.[0]||null)}/><b>{file?file.name:"Seleccione ou arraste um ficheiro"}</b><small>Excel (.xlsx) ou CSV · até 500 MB</small></label><div className="template-fields">Campos mínimos: REGIME, year, month, SH8, SumOfquantity, unit e SumOfMilUSD.</div><button disabled={!file} onClick={()=>setStage(1)}>Validar ficheiro →</button></>}{stage===1&&<><div className="validation-list"><p>✓ Estrutura seleccionada para validação</p><p>✓ Identificadores reservados à camada protegida</p><p>✓ Destino privado: ice-source-files</p></div>{message&&<p className="form-message">{message}</p>}<button disabled={busy} onClick={storeFile}>{busy?"A guardar…":"Guardar e catalogar →"}</button></>}{stage===2&&<><div className="ready-state"><b>Ficheiro recebido</b><p>{message}</p></div><button onClick={close}>Concluir</button></>}</div></div>}</>;
}
