"use client";
import {useLayoutEffect,useMemo,useRef,useState} from "react";
import dataset from "../data/scenarios.json";
import {mozambiquePaths} from "./mozambique-paths";
type GeoRow={flow:string;year:number;continent:string;country:string;lat:number;lon:number;value:number};
type ProvinceRow={flow:string;year:number;province:string;value:number};
const fmt=(n:number)=>n.toLocaleString("pt-PT",{maximumFractionDigits:0});
const continentName=(v:string)=>v==="Oceania"?"Oceânia":v;
const validContinent=(v:string)=>!['#N/A','0','Não classificado','Outros Países Não Classificados','Zona Neutra'].includes(v);
const provinceName=(v:string)=>v.replace('MAPUTO PROVÍNCIA','MAPUTO PROV').replace('ZAMBÉZIA','ZAMBEZIA');
const svgProvince:Record<string,string>={NIASSA:'Niassa','CABO DELGADO':'Cabo Delgado',NAMPULA:'Nampula',ZAMBEZIA:'Zambezia',TETE:'Tete',MANICA:'Manica',SOFALA:'Sofala',INHAMBANE:'Inhambane',GAZA:'Gaza','MAPUTO PROV':'Maputo','MAPUTO CIDADE':'Maputo City'};
export default function GeoTrade(){
 const[year,setYear]=useState(2025),[continent,setContinent]=useState(''),[country,setCountry]=useState('');
 const[provinceCenters,setProvinceCenters]=useState<Record<string,[number,number]>>({});
 const provinceRefs=useRef<Record<string,SVGPathElement|null>>({});
 const geo=dataset.geography as GeoRow[],provs=dataset.provinces as ProvinceRow[];
 const continents=useMemo(()=>Array.from(new Set(geo.map(r=>continentName(r.continent)).filter(validContinent))).sort((a,b)=>a.localeCompare(b,'pt')),[geo]);
 const countries=useMemo(()=>Array.from(new Set(geo.filter(r=>!continent||continentName(r.continent)===continent).map(r=>r.country).filter(v=>v&&v!=='#N/A'&&v!=='Não identificado'))).sort((a,b)=>a.localeCompare(b,'pt')),[geo,continent]);
 const partner=useMemo(()=>{const m=new Map<string,{country:string,continent:string,lat:number,lon:number,exports:number,imports:number}>();geo.filter(r=>r.year===year&&validContinent(continentName(r.continent))).forEach(r=>{const old=m.get(r.country)||{country:r.country,continent:continentName(r.continent),lat:r.lat,lon:r.lon,exports:0,imports:0};old[r.flow==='EXP'?'exports':'imports']+=r.value;if(r.lat||r.lon){old.lat=r.lat;old.lon=r.lon}m.set(r.country,old)});return Array.from(m.values()).filter(r=>(!continent||r.continent===continent)&&(!country||r.country===country)).map(r=>({...r,balance:r.exports-r.imports})).sort((a,b)=>b.exports+b.imports-a.exports-a.imports)},[geo,year,continent,country]);
 const max=Math.max(1,...partner.map(r=>r.exports+r.imports)),totals=partner.reduce((a,r)=>({exports:a.exports+r.exports,imports:a.imports+r.imports}),{exports:0,imports:0});
 const provinceData=useMemo(()=>{const m=new Map<string,{province:string,exports:number,imports:number}>();provs.filter(r=>r.year===year).forEach(r=>{const n=provinceName(r.province),o=m.get(n)||{province:n,exports:0,imports:0};o[r.flow==='EXP'?'exports':'imports']+=r.value;m.set(n,o)});return Array.from(m.values()).map(r=>({...r,balance:r.exports-r.imports}))},[provs,year]);
 const pmax=Math.max(1,...provinceData.map(r=>r.exports+r.imports));
 useLayoutEffect(()=>{const next:Record<string,[number,number]>={};for(const [name,node] of Object.entries(provinceRefs.current)){if(!node)continue;const b=node.getBBox();next[name]=[b.x+b.width/2,b.y+b.height/2]}setProvinceCenters(next)},[]);
 return <section className="geo-section"><div className="geo-head"><div><span>GEOGRAFIA DO COMÉRCIO</span><h2>Parceiros comerciais e províncias</h2><p>Seleccione primeiro o continente e depois o país. Os círculos representam o valor total de exportações e importações, em mil USD.</p></div><label>Ano<select value={year} onChange={e=>setYear(+e.target.value)}>{[2022,2023,2024,2025].map(y=><option key={y}>{y}</option>)}</select></label></div>
 <div className="geo-filters"><label><b>1</b> Continente<select value={continent} onChange={e=>{setContinent(e.target.value);setCountry('')}}><option value="">Seleccione o continente</option>{continents.map(c=><option key={c}>{c}</option>)}</select></label><label><b>2</b> País<select value={country} disabled={!continent} onChange={e=>setCountry(e.target.value)}><option value="">Todos os países</option>{countries.map(c=><option key={c}>{c}</option>)}</select></label><article><small>EXPORTAÇÕES</small><strong>{fmt(totals.exports)}</strong></article><article><small>IMPORTAÇÕES</small><strong>{fmt(totals.imports)}</strong></article><article className={totals.exports-totals.imports<0?'deficit':'surplus'}><small>BALANÇA</small><strong>{fmt(totals.exports-totals.imports)}</strong></article></div>
 <div className="maps-grid"><article className="map-card world-card"><div className="map-title"><div><span>MAPA MUNDO</span><h3>{country||continent||'Todos os parceiros'}</h3><small>{partner.length} parceiro{partner.length===1?'':'s'} representado{partner.length===1?'':'s'}</small></div><div className="map-legend"><i className="exp"/> Exportações <i className="imp"/> Importações</div></div><svg viewBox="0 0 960 410" className="world-map" role="img" aria-label="Mapa mundial completo das exportações e importações"><image href="https://ice-mz.sergiom-ndimande.chatgpt.site/maps/world-partners.svg" width="960" height="410" preserveAspectRatio="none"/><g className="moz-origin"><circle cx={(32.5732+180)/360*960} cy={(90+25.9692)/180*410} r="6"/><text x={(32.5732+180)/360*960+10} y={(90+25.9692)/180*410+4}>Moçambique</text></g>{partner.filter(r=>Number.isFinite(r.lat+r.lon)&&(r.lat||r.lon)).map(r=>{const cx=(r.lon+180)/360*960,cy=(90-r.lat)/180*410,er=3+Math.sqrt(r.exports/max)*19,ir=3+Math.sqrt(r.imports/max)*19;return <g key={r.country} className="map-point"><circle className="export-point" cx={cx-2.5} cy={cy} r={er}/><circle className="import-point" cx={cx+2.5} cy={cy} r={ir}/><title>{r.country}: Exportações {fmt(r.exports)} · Importações {fmt(r.imports)} · Saldo {fmt(r.balance)} mil USD</title></g>})}</svg><div className="partner-table"><table><thead><tr><th>País</th><th>Exportações</th><th>Importações</th><th>Saldo</th></tr></thead><tbody>{partner.slice(0,8).map(r=><tr key={r.country}><td>{r.country}</td><td>{fmt(r.exports)}</td><td>{fmt(r.imports)}</td><td className={r.balance<0?'negative':'positive'}>{fmt(r.balance)}</td></tr>)}</tbody></table></div></article>
 <article className="map-card moz-card"><div className="map-title"><div><span>MAPA DE MOÇAMBIQUE</span><h3>Comércio por província</h3><small>Limites provinciais oficiais de referência</small></div><div className="map-legend"><i className="exp"/> Exportações <i className="imp"/> Importações</div></div><div className="moz-layout"><svg viewBox="0 0 1000 1000" className="moz-map" role="img" aria-label="Mapa provincial de Moçambique com exportações e importações"><g className="moz-provinces">{mozambiquePaths.map(p=><path key={p.id} ref={node=>{provinceRefs.current[p.name]=node}} d={p.d}><title>{p.name}</title></path>)}</g>{provinceData.map(r=>{const p=provinceCenters[svgProvince[r.province]];if(!p)return null;const er=10+Math.sqrt(r.exports/pmax)*35,ir=10+Math.sqrt(r.imports/pmax)*35;return <g key={r.province} className="province-point"><circle className="export-point" cx={p[0]-7} cy={p[1]} r={er}/><circle className="import-point" cx={p[0]+7} cy={p[1]} r={ir}/><title>{r.province}: Exportações {fmt(r.exports)} · Importações {fmt(r.imports)} · Saldo {fmt(r.balance)} mil USD</title></g>})}</svg><div className="province-list">{[...provinceData].sort((a,b)=>b.exports+b.imports-a.exports-a.imports).map(r=><div key={r.province}><b>{r.province}</b><span>Exp. {fmt(r.exports)}</span><span>Imp. {fmt(r.imports)}</span></div>)}</div></div></article></div><p className="geo-note">Fonte geográfica: campos Continente, Country_name_pt, Latitude, Longitude e PROVÍNCIA dos ficheiros aduaneiros. Verde representa exportações e dourado, importações; o tamanho dos círculos é proporcional ao valor em mil USD. Passe o cursor sobre os círculos para consultar país ou província, valores e saldo. A província representa o local registado na declaração, não necessariamente a origem produtiva ou o destino final da mercadoria.</p></section>
}
